### ISSUE TITLE
Container broke and app is blank, how to reset settings?

### ISSUE THREAD

**Issue by Matiasgroen** [sailfish-containers/harbour-containers#28]
I wanted to add an Alpine container but during setup it froze. After I killed the app and opened it again the main screen is now blank. I have already deleted the Alpine LXC files but it seems like the app is still looking for them even after a reinstall. How can I reset everything?

Below is the terminal output from launching the app:

```
[D] unknown:0 - Using Wayland-EGL
[D] onCompleted:12 - DB created.
[W] unknown:12 - file:///usr/share/harbour-containers/qml/harbour-containers.qml:12:5: QML Daemon: QDBusError("org.freedesktop.DBus.Python.subprocess.CalledProcessError", "Traceback (most recent call last):\n  File \"/usr/lib/python3.8/site-packages/dbus/service.py\", line 711, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/harbour-containers/service/daemon.py\", line 475, in get_containers\n    self._refresh()\n  File \"/usr/share/harbour-containers/service/daemon.py\", line 113, in _refresh\n    self.containers = lxc.get_containers()\n  File \"/usr/share/harbour-containers/service/libs/lxc.py\", line 41, in get_containers\n    cmd_out = subprocess.check_output(['lxc-info', '-n', container,'-p','-s','-S']).decode().split(\"\\n\")\n  File \"/usr/lib/python3.8/subprocess.py\", line 415, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib/python3.8/subprocess.py\", line 516, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['lxc-info', '-n', 'Alpine', '-p', '-s', '-S']' returned non-zero exit status 1.\n")
```

**Comment by Kabouik** [comment]
Hey, great news, it'd be nice to have Alpine among the compatible containers.

I'm not sure what the issue is and have no Sailfish device at hand to replicate (mine is currently running Droidian), but I would say the daemon needs to be restarted. Could you try the following?

```sh
ps aux | grep daemon.py
kill -0 <the PID you'll find in the list>
```

Also, what LXC files did you delete? As far as I remember,  the the container is created in `/home/.lxc/containername`, but there are also configuration files in `/var/lib/lxc/` which you may want to clean too. Application files (like `daemon.py`) should be in `/usr/share/harbour-containers`, but can be left intact. If you want to restart clean, I believe you should try deleting the content relative to your Alpine attempt from the two former folders, and then try restarting the daemon (or reboot).

**Comment by Matiasgroen** [comment]
I missed /var/lib/lxc/. Cleaning that did the trick and my new Alpine container works now. Thank you!
